### ISSUE TITLE
Add support to <br>

### ISSUE THREAD

**Issue by tomaswarynyca** [appleboy/drone-telegram#100]
In my case I don't use multiple messages in the template, I use a generic one. 
If I use html the text is put all together so you need to add a `<br>` to make a line break.

**Comment by appleboy** [comment]
Good point.

**Comment by tomaswarynyca** [comment]
If not see how to make it not put everything together
Here is an example of my code
```
<a>Hi<a>
<b>Hi<b>
```
`This returns` Hi**Hi**

`You should return`
Hi
**Hi**

**Comment by SershoCode** [comment]
I agree with this, it is a very necessary functionality. I couldn't make a line break in any way. Please do it

**Comment by appleboy** [comment]
Try it out:

```diff
  - name: send telegram notification
    image: appleboy/drone-telegram
    settings:
      token: xxxxxxxxxx
      to: telegram_user_id
      format: HTML
+     message: >
+       Test HTML Format from file
+       <a href='https://google.com'>Google .com 1</a>
+       <a href='https://google.com'>Google .com 2</a>
+       <a href='https://google.com'>Google .com 3</a>
+       <a href='https://google.com'>Google .com 4</a>
```
