### ISSUE TITLE
Bold in markdown does not work

### ISSUE THREAD

**Issue by tomaswarynyca** [appleboy/drone-telegram#101]
When entering `**text**` the bold is not reflected in the message.

**Comment by Techassi** [comment]
You should use `*bold*`

**Comment by tomaswarynyca** [comment]
> You should use `*bold*`

you say only with a *?

**Comment by Techassi** [comment]
Yep indeed. Can confrim this works!

**Comment by tomaswarynyca** [comment]
Great! Thanks for the help @Techassi
