### ISSUE TITLE
Invalid version of github.com/drone/drone-template-lib

### ISSUE THREAD

**Issue by Techassi** [appleboy/drone-telegram#102]
You changed the version of `github.com/drone/drone-template-lib` from v1.0.0 in this [commit](https://github.com/appleboy/drone-telegram/commit/47352c6cca24f624b46e5093a77f41a1ba499bd5#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L6) to v1.0.1-x to fix the issue in #89 and #92. Also see [#47](https://github.com/drone-plugins/drone-webhook/issues/47)

With your latest release / version v1.3.9 you accidentally changed the version of `github.com/drone/drone-template-lib` back to v1.0.0 which breaks the templating functions `duration`, `datetime` and `since` because these functions expect a `float64` value but _build.started_ and _build.finished_ are `int64` values.

I guess there are two possible solutions: Reverting / changing back to version v1.0.1-x or opening a PR on the [drone-template-lib](https://github.com/drone/drone-template-lib) project to release a new version with the correct values; the master branch already has the correct `int64` type, but the released branch v1.0.0 uses the old `float64` type.

**Comment by Techassi** [comment]
Any update on this @appleboy ?

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
I find another issue in `duration` function. I will fire a new issue in  drone-template-lib.

**Comment by appleboy** [comment]
@Techassi bump to https://github.com/appleboy/drone-telegram/releases/tag/v1.3.10 Please try it out.

**Comment by Techassi** [comment]
Can confirm this now works without any issues (tested with local binary):

```shell
./drone-telegram --token <token> --to <to> --build.started 1625309840
```
with template
```
Date/Time: {{datetime build.started "2006-01-02 15:04:05 -0700" "Europe/Berlin"}}
```
returns
```
Date/Time: 2021-07-03 12:57:20 +0200
```

Will now check out the updated docker image!

**Comment by appleboy** [comment]
@Techassi Thanks for your testing report.
