### ISSUE TITLE
Add map chat_id and email and send messages only author

### ISSUE THREAD

**Issue by orloffv** [appleboy/drone-telegram#21]
like
```
author:
  - chat_id:author_email
```

**Comment by orloffv** [comment]
maybe ok if there is no coincidence with the author send to "to" - same default

**Comment by appleboy** [comment]
@orloffv 

```
to:
  - chat_id:author_email
  - chat_id
```

The first record will check author email from commit log. Second record doesn't check author email by default behavior.

**Comment by orloffv** [comment]
cool!

**Comment by appleboy** [comment]
OK, I will take it and also support `drone-facebook`, `drone-gtalk` and `drone-line` plugin.
