### ISSUE TITLE
Add ONLY_MATCH_EMAIL flag

### ISSUE THREAD

**Issue by appleboy** [appleboy/drone-telegram#23]
### config

```
to:
  - 1:1@email.com
  - 2:2@gmail.com
  - 3:3@gmail.com
  - 4:4@gmail.com
  - 5:5@gmail.com
  - 6
```

The chat_id (`6`) contain all team members like 1~5@email.com. if author email match `1@email.com`, member (`1`) will get direct message and another from chat_id (`6`). This is the default behavior.

### ONLY_MATCH_EMAIL

if set `ONLY_MATCH_EMAIL` as `true`, drone don't send message to chat_id (`6`).

**Comment by orloffv** [comment]
And if committer email is **another**@gmail.com then send message only chat_id (6).
