### ISSUE TITLE
To parameter with 'username'

### ISSUE THREAD

**Issue by Alber70g** [appleboy/drone-telegram#32]
Thank you so much for this plugin. 
I've got one issue: Should the to parameter be the username of the user that needs to receive a notification? Or if not, where can I find my UserId?

**Comment by appleboy** [comment]
@Alber70g You need to use webhooks to get your user unique ID.

**Comment by Alber70g** [comment]
I found that @userinfobot echo's some userinfo, including userid.

**Comment by Alber70g** [comment]
I've added a PR #33 to add this to the DOCS
