### ISSUE TITLE
{{#success ..}} {{else}} does not work

### ISSUE THREAD

**Issue by tarmaciltur** [appleboy/drone-telegram#38]
I can't make a custom message with {{#success ..}} {{else}}. Without {{else}} works well.
this is my config
```
pipeline:
  telegram:
    image: appleboy/drone-telegram
    token: $PLUGIN_TOKEN
    to: $PLUGIN_TO
    secrets: [ plugin_token, plugin_to ]
    message: |
      {{repo.owner}}/{{repo.name}}
      Branch: {{build.branch}}
      Commit: {{truncate build.commit 8}}
      Autor: {{build.author}}
      {{#success build.status}}
      Compila correctamente.
      {{else}}
      No compila.
      {{/success}}
```
this is the error message
> Parse error on line 8:
Expecting OpenEndBlock, got: 'EOF'

**Comment by appleboy** [comment]
try the following example codde.

```diff
pipeline:
  telegram:
    image: appleboy/drone-telegram
    token: $PLUGIN_TOKEN
    to: $PLUGIN_TO
    secrets: [ plugin_token, plugin_to ]
+   message: >
+     {{#success build.status}}
+       build {{build.number}} succeeded. Good job.
+     {{else}}
+       build {{build.number}} failed. Fix me please.
+     {{/success}}
```

**Comment by tarmaciltur** [comment]
With the suggested example code, and replacing the line "**message: |**" to "**message: >**" in my code, the result is the same

> Parse error on line 1:
> Lexer error
> Token: Error{"Unexpected character in expression: '}'"}

**Comment by fredix** [comment]
Hi @tarmaciltur 
I had the same error, It works now without space after { 

```
  message: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}

```

@appleboy can you update your documentation http://plugins.drone.io/appleboy/drone-telegram/ ?
I mean change | with > and remove space after {{  and before }}

**Comment by appleboy** [comment]
@fredix See https://github.com/drone/drone-plugin-index/issues/44

**Comment by appleboy** [comment]
Already update docs http://plugins.drone.io/appleboy/drone-telegram/
