### ISSUE TITLE
Better debugging when a message does not come through

### ISSUE THREAD

**Issue by Cysioland** [appleboy/drone-telegram#47]
Currently it returns no error even when my message does not come through on Telegram

**Comment by appleboy** [comment]
I will add debug mode to get the response from Telegram bot.

**Comment by sokoow** [comment]
+1 here, I am trying to make it working but can't, no messages are coming through

**Comment by tlwt** [comment]
Same here - I tried to send something, even without using secrets I cannot get a message out.

**Comment by appleboy** [comment]
@tlwt What kind of debug message do you want? drone will output the error message if missing secrets.

**Comment by levchik** [comment]
First of all, thanks for the plugin. I'm experiencing the same exact problem, It just exit codes with 0, but no actual message is received. Is there any way for plugin to print out feedback about what's wrong?

**Comment by appleboy** [comment]
Enable the debug mode:

```yml
debug: true
```
