### ISSUE TITLE
HTML Entities aren't decoded (only for Gogs?)

### ISSUE THREAD

**Issue by rafi** [appleboy/drone-telegram#50]
HTML entities aren't decoded for `build.message`. (Using the GOGS integration)

![image](https://user-images.githubusercontent.com/147918/29888196-bc014afe-8dc8-11e7-8fc0-f4c894424e99.png)

**Comment by appleboy** [comment]
@rafi Could you provide the full commit message?

**Comment by rafi** [comment]
@appleboy the original commit msg: `Freakin' macOS isn't fully case-sensitive..`
However it shows in Telegram like this: `Freakin&apos; macOS isn&apos;t fully case-sensitive..`

**Comment by appleboy** [comment]
@rafi Can't reproduce now. Please try the latest image.

<img width="780" alt="screen shot 2017-12-02 at 5 29 46 pm" src="https://user-images.githubusercontent.com/21979/33513977-99a06d7a-d786-11e7-9705-943b0f01f939.png">

maybe only for the Gogs?

**Comment by rafi** [comment]
@appleboy It still happens, probably only in Gogs...

**Comment by dmlambea** [comment]
@rafi it also happens in Gitea, that is my case. Gitea is a fork of Gogs, BTW.
