### ISSUE TITLE
{{build.branch}} and {{build.commit}} not working

### ISSUE THREAD

**Issue by Electrofenster** [appleboy/drone-telegram#53]
I tried to get these Information in my Message but the only thing I got was an empty message. The other variables I use work.

I have one more question. Does something like this work?
```
file:
      - /drone/src/github.com/{{repo.owner}}/{{repo.name}}/commit/{{build.commit}}/README.md
```

**Comment by appleboy** [comment]
@Electrofenster What is your drone version? You can try the following in drone 0.8 version.

```
/drone/src/github.com/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}/commit/${DRONE_COMMIT_SHA}/README.md
```
