### ISSUE TITLE
getting connection refused

### ISSUE THREAD

**Issue by Franselbaer** [appleboy/drone-telegram#58]
I installed the drone plugin as mentioned. Created a bot, got a token and tried to send a message but getting:

``` 
2018/03/07 12:44:34 Post https://api.telegram.org/bot4xxxxxxxxx9:AAxxxxxxxxxxxxxxxDc1-mlxxxxxxxxxcYglhQ/getMe: dial tcp 149.154.167.220:443: getsockopt: connection refused
```

**Comment by Franselbaer** [comment]
🤔 In my browser it works. But Drone runs on a server with a server ip....

**Comment by KennethMa** [comment]
Same error..

**Comment by xiaoguiSniper** [comment]
same error! so,I wonder if you have any solutions?

**Comment by appleboy** [comment]
Can' reproduce in cloud.drone.io See: https://cloud.drone.io/appleboy/drone-telegram/27/1/5
