### ISSUE TITLE
on error bot token displayed in drone logs

### ISSUE THREAD

**Issue by vtolstov** [appleboy/drone-telegram#65]
```
2018/10/18 00:43:56 Post https://api.telegram.org/bot667338145:HFHDFHDHFHD-lViTaORT3piWK5slHj59dfM/getMe: read tcp 172.19.0.2:44146->149.154.167.220:443: read: connection reset by peer
```

i think that bot token needs to be hidden

**Comment by appleboy** [comment]
The error message from https://github.com/go-telegram-bot-api/telegram-bot-api repo. I just print an error message for debugging.

**Comment by vtolstov** [comment]
i known, but why not strings.Replace(err.Error(), TELEGRAM_TOKEN, "XXXXXXXXXXXXXXXXXX") ?

**Comment by appleboy** [comment]
@vtolstov Can you send the PR?

**Comment by appleboy** [comment]
I will take it.
