### ISSUE TITLE
ARM version doesn't work

### ISSUE THREAD

**Issue by Crazy-kun** [appleboy/drone-telegram#69]
This image doesn't work on OrangePI armv7 arch:
standard_init_linux.go:207: exec user process caused "exec format error"

**Comment by appleboy** [comment]
@Crazy-kun Can you help to try `1.4.1-linux-arm64` tag of docker?

See: https://cloud.docker.com/repository/docker/appleboy/drone-telegram/tags

**Comment by Crazy-kun** [comment]
Seems like container is works, no error about exec format now. But i got following error: "missing telegram token or user list". Maybe i made mistake in .yml config.
`      token: "123456789:xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      to:
          - bot_name`
It is right?

**Comment by appleboy** [comment]
@Crazy-kun Please get channel id as the following:

```
$ curl https://api.telegram.org/bot<token>/getUpdates
```

See the result: (get chat id like 65382999)

```json
{
  "ok": true,
  "result": [
    {
      "update_id": 664568113,
      "message": {
        "message_id": 8423,
        "from": {
          "id": 65382999,
          "is_bot": false,
          "first_name": "Bo-Yi",
          "last_name": "Wu (appleboy)",
          "username": "appleboy46",
          "language_code": "en"
        },
        "chat": {
          "id": 65382999,
          "first_name": "Bo-Yi",
          "last_name": "Wu (appleboy)",
          "username": "appleboy46",
          "type": "private"
        },
        "date": 1550333434,
        "text": "?"
      }
    }
  ]
}
```

```
to: 65382999
```

**Comment by Crazy-kun** [comment]
I got chat id as you said and replaced name with this id:
`to: 265858723`
But i still receive same error.

**Comment by appleboy** [comment]
post your YAML file.

**Comment by Crazy-kun** [comment]
`kind: pipeline
name: drone-node

platform:
    os: linux
    arch: arm

steps:
    - name: deploy
      image: crazyapelsin/dind-compose:1.0.0
      volumes:
          - name: dockersock
            path: /var/run/docker.sock
      commands:
          - docker-compose build
          - docker-compose stop
          - docker-compose up -d
    - name: telegram
      image: appleboy/drone-telegram:1.4.1-linux-arm
      token: "12345678:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      to: 265858723
      message: >
          {{#success build.status}}
            build {{build.number}} succeeded. Good job.
          {{else}}
            build {{build.number}} failed. Fix me please.
          {{/success}}
volumes:
    - name: dockersock
      host:
          path: /var/run/docker.sock`

**Comment by appleboy** [comment]
See the plugin section of docs: https://docs.drone.io/user-guide/pipeline/migrating/

**Comment by Crazy-kun** [comment]
My mistake, all works fine now. Thanks for help!
