### ISSUE TITLE
Function {{datetime build.started}} not working

### ISSUE THREAD

**Issue by roman7722** [appleboy/drone-telegram#75]
When using the {{datetime build.started}} function, an error is displayed:
Evaluation error: Helper 'datetime' called with wrong number of arguments, needed 3 but got 1
How can I fix this?

**Comment by roman7722** [comment]
If you call like this:

`{{datetime @build.started "%Y-%m-%d %H:%M:%S" "MSK"}}`

there is no error, but the result in the message comes wrong:

`1552198752 %Y-%m-%d %H:%M:%S`

**Comment by mfontani** [comment]
Output is declared using the format given on https://golang.org/pkg/time/#Parse - which isn't strftime-like.

In your case, `{{ datetime @build.started "2006-01-02 15:04:05" "MSK" }}` ought to work. Could you try that?

**Comment by roman7722** [comment]
Many thanks @mfontani! Everything works, but the time zone does not change, and the value is shown in GMT. I tried to substitute different time zones (

**Comment by mfontani** [comment]
@roman7722 I believe using `"Europe/Moscow"` ought to work.

Best I can tell the `datetime` helper comes from the drone-facebook repo (see https://github.com/appleboy/drone-facebook/blob/77ae7a2b13cc1a403b05c0728e685f6aa255be73/template/template.go#L95) and it silently ignores errors related to a "bad" timezone being given, and uses the local time if an error comes up when loading it via LoadLocation.

I've put `MSK` in the code samples in https://golang.org/pkg/time/#LoadLocation and indeed it's not recognised... but using `Europe/Moscow` works properly (you'll have to expand the Example, switch `America/Los_Angeles` in the example for `Europe/Moscow` and hit `Run`).

If you're unsure about whether the timezone is correct or wrong, plug it into the `LoadLocation` help page above, hit "run" and see whether any error comes up.

HTH

**Comment by roman7722** [comment]
Thanks for answer @mfontani! I use this string
`{{ datetime @build.started "02-Jan-2006 15:04:05 MST" "Europe/Moscow" }}`
and get in the result

**Comment by appleboy** [comment]
I move the template engine to `github.com/drone/drone-template-lib/template`
