### ISSUE TITLE
Telegram connection reset by peer

### ISSUE THREAD

**Issue by rakshith-ravi** [appleboy/drone-telegram#86]
Hey,

Thanks for this great integration. We've been using this for the past 6 months now and it has been working great for us. For the past two weeks, however, we keep getting this message on our build logs:

```
Post https://api.telegram.org/bot[secret:telegram_token]/getMe: read tcp 192.168.128.3:36920->149.154.167.220:443: read: connection reset by peer
```

This causes our build to fail and the message doesn't get delivered to our telegram group. Could you please help me identify the issue and what I can do to fix this?

**Comment by icecream78** [comment]
@rakshith-ravi Hi. Is url https://api.telegram.org/bot[secret:telegram_token]/getMe accessible via manual curl call?

**Comment by rakshith-ravi** [comment]
From my system? Yes. From the server, however, it's not. For some reason, the connection keeps getting cut. Not sure why.

**Comment by icecream78** [comment]
I think, that you have trouble on your server. I have same problem, when use plugin, because telegram blocked in Russia. For the testing puproses, try specify socks5 proxy in plugin and trigger CI. Interesting to know is it helped you.

**Comment by appleboy** [comment]
Try the http, https or socks5 proxy:

```diff
  - name: send telegram notification
    image: appleboy/drone-telegram
    settings:
      token: xxxxxxxxxx
      to: telegram_user_id
      message: send message using custom socks5 URL
+     socks5: socks5://67.204.21.1:64312
```
