### ISSUE TITLE
Using {{since build.started}} throws Evaluation error type float64 but it should be int64

### ISSUE THREAD

**Issue by waterdrop01** [appleboy/drone-telegram#92]
Hello, 
I added `{{since build.started}}` to my `.drone.yml` as per the doc (http://plugins.drone.io/appleboy/drone-telegram/). But notification fails.

Here is the error message:
```
Evaluation error: Helper since called with argument 0 with type float64 but it should be int64
```

Any idea? Thanks a lot!

**Comment by appleboy** [comment]
Try `appleboy/drone-telegram:linux-amd64` image
