### ISSUE TITLE
ENV_FILE seems to be ignored

### ISSUE THREAD

**Issue by smnbbrv** [appleboy/drone-telegram#93]
Hi @appleboy 

I tried to fix a vary annoying #90 with setting ENV_FILE environment variable that is described here https://github.com/appleboy/drone-telegram#usage

However it seems to be totally ignored even when I clone it and run locally.

Is this option still supported?

**Comment by appleboy** [comment]
@smnbbrv let me check.

**Comment by appleboy** [comment]
@smnbbrv 

```
docker run --rm \
  -e PLUGIN_ENV_FILE=your_env_file_path \
  -v $(pwd):$(pwd) \
  -w $(pwd) \
  appleboy/drone-telegram
```
