### ISSUE TITLE
Template variables from file

### ISSUE THREAD

**Issue by dbolotin** [appleboy/drone-telegram#97]
Our build pipeline assigns artefact versions "on the fly" during the build process. I wanted to include the value into the message about the successful build. Currently there is no way to pass values from the build process to the message template (please correct me it there is a way of doing it).

I think the easiest and the most generic way of providing such functionality would be to allow importing of `json` formatted file and adding it's content to the list of template variables, e.g. adding a parameter `template_vars_from_file`. What do you think? I can submit a pull request.

**Comment by appleboy** [comment]
fixed in #98
